apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubiya-assessment
  labels:
    app: kubiya-assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubiya-assessment
  template:
    metadata:
      labels:
        app: kubiya-assessment
    spec:
      containers:
      - name: kubiya-assessment
        image: kubiya-assessment:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: production
